services:
  - type: worker  # ⚠️ غيرنا من web إلى worker
    name: telegram-video-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python auto.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
